# Generated by Django 5.2.12 on 2026-03-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_initial_password_user_security_a1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('file_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'file_processing_logs',
                'ordering': ['-processed_at'],
            },
        ),
    ]
