# Generated by Django 5.2.12 on 2026-03-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fileprocessinglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprocessinglog',
            name='details',
        ),
        migrations.AddField(
            model_name='fileprocessinglog',
            name='final_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileprocessinglog',
            name='software_count',
            field=models.TextField(blank=True, null=True),
        ),
    ]
