# Generated by Django 5.2.12 on 2026-03-22 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_fileprocessinglog_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocessinglog',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
