AMOUNT_TOLERANCE = 100.0
PROCESSED_DIR = "Matched_Statemants"

TITLE_WORDS = {"MR", "MRS", "MS", "MISS", "DR", "SHRI", "SMT", "MESSRS"}
FIRM_KEYWORDS = {
    "AGENCY", "AGENCIES", "ENTERPRISE", "ENTERPRISES", "TRADERS", "TRADING",
    "INDUSTRIES", "INDUSTRY", "CO", "COMPANY", "LLP", "LTD", "LIMITED",
    "ASSOCIATES", "TRUST", "FOUNDATION", "CENTRE", "CENTER",
    "STORE", "STORES", "SHOP", "SOLUTIONS", "PVT", "PRIVATE"
}

SHORT_BANK_NAMES = {
    "Axis Bank, India": "AXIS",
    "AU Small Finance Bank, India": "AUBL",
    "Bank of Baroda, India": "BOB",
    "Bank of India, India": "BOI",
    "Bandhan Bank, India": "BDBL",
    "Bank of Maharashtra, India": "BOM",
    "Canara Bank, India": "CNRB",
    "Catholic Syrian Bank, India": "CSB",
    "Central Bank of India, India": "CBI",
    "Citibank, India": "CITI",
    "City Union Bank, India": "CUB",
    "DBS Bank, India": "DBS",
    "DCB, India": "DCB",
    "Dhanalakshmi Bank Ltd., India": "DLXB",
    "Deutsche Bank, India": "DEUT",
    "Equitas Bank, India": "ESFB",
    "ESAF Small Finance Bank, India": "ESAF",
    "Federal Bank, India": "FDRL",
    "HDFC Bank, India": "HDFC",
    "HSBC, India": "HSBC",
    "ICICI Bank, India": "ICICI",
    "IDFC First Bank, India": "IDFC",
    "IDFC FIRST Bank, India": "IDFC",
    "Indian Bank, India": "IDIB",
    "IDBI, India": "IDBI",
    "Indian Overseas Bank, India": "IOB",
    "IndusInd Bank, India": "INDB",
    "Jana Small Finance Bank Ltd, India": "JSFB",
    "J&K Bank, India": "JAKA",
    "Karur Vysya Bank, India": "KVB",
    "Karnataka Bank, India": "KARB",
    "Kotak Mahindra Bank, India": "KKBK",
    "Punjab National Bank, India": "PNB",
    "Punjab and Sind Bank, India": "PSIB",
    "RBL Bank, India": "RBL",
    "RBL (Ratnakar) Bank, India": "RBL",
    "South Indian Bank, India": "SIB",
    "State Bank of India, India": "SBI",
    "Standard Chartered Bank, India": "SCB",
    "Tamilnad Mercantile Bank Ltd, India": "TMB",
    "Tamilnad Mercantile Bank Ltd., India": "TMB",
    "Union Bank of India, India": "UBI",
    "Ujjivan Bank, India": "UJVN",
    "UCO Bank, India": "UCO",
    "Yes Bank, India": "YBL",
}

BANK_IFSC_PREFIXES = {
    "AXIS": "UTIB",
    "AUBL": "AUBL",
    "BOB": "BARB",
    "BOI": "BKID",
    "BDBL": "BDBL",
    "BOM": "MAHB",
    "CNRB": "CNRB",
    "CSB": "CSBK",
    "CBI": "CBIN",
    "CITI": "CITI",
    "CUB": "CIUB",
    "DBS": "DBSS",
    "DCB": "DCBL",
    "DLXB": "DLXB",
    "DEUT": "DEUT",
    "ESFB": "ESFB",
    "ESAF": "ESMF",
    "FDRL": "FDRL",
    "HDFC": "HDFC",
    "HSBC": "HSBC",
    "ICICI": "ICIC",
    "IDFC": "IDFB",
    "IDFC": "IDFB",
    "IDIB": "IDIB",
    "IDBI": "IBKL",
    "IOB": "IOBA",
    "INDB": "INDB",
    "JSFB": "JSFB",
    "JAKA": "JAKA",
    "KVB": "KVBL",
    "KARB": "KARB",
    "KKBK": "KKBK",
    "PNB": "PUNB",
    "PSIB": "PSIB",
    "RBL": "RATN",
    "RBL": "RATN",
    "SIB": "SIBL",
    "SBI": "SBIN",
    "SCB": "SCBL",
    "TMB": "TMBL",
    "UBI": "UBIN",
    "UJVN": "UJVN",
    "UCO": "UCBA",
    "YBL": "YESB",
}