import pandas as pd
import re

# ── Bank alias normalisation ───────────────────────────────────────────────────
_BANK_ALIASES = {
    'UBIN': 'UBI',
    'SBIN': 'SBI',
    'YES':  'YBL',
    'YESB': 'YBL',
}

# ── Common fallback reference pattern ─────────────────────────────────────────
_REF_PATTERN = r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)"

# ── Raw pattern strings, keyed by bank code ───────────────────────────────────
# Banks that only need the generic ref# fallback are listed at the bottom.
_RAW_PATTERNS: dict[str, list[str]] = {
    "CNRB": [
        r"(?i)^IB\s+NEFT\s+Dr\s+([A-Z0-9]+)\s+",
        r"(?i)^IB-IMPS-DR.*\/(\d+)\s+\(Ref#",
        r"(?i)\bIB-IMPS-DR//.*?//\d{2}/\d{2}/\d{4}\d{2}:\d{2}:\d{2}/(\d{9,20})",
        r"(?i)^IB\s+IFT\s+(\d+)\s+",
        r"(?i)\bIB IFT\s+\d+\s+(\d{9,20})\b",
        r"(?i)^IB\s+ITG\s+([0-9]+)\s+",
        r"(?i)^NEFT\s+Dr-([A-Z0-9]+)-",
        r"(?i)^RTGS\s+Dr-([A-Z0-9]+)-",
        r"(?i)^RTGS\s+Cr-([A-Z0-9]+)-",
        r"(?i)^RTGS.*?([A-Z]{5}\d{17})-",
        r"(?i)^NEFT\s+Cr-([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?RTGS\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?NEFT\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?IMPS\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UPI\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bBY TRANSFER/NEFT\s+.*?/XUTR/([A-Z0-9]{8,})",
        r"(?i)\bBY TRANSFER/NEFT\s+.*?([A-Z0-9]{10,})\s*$",
        r"(?i)\bBY TRANSFER/RTGS\w*.*?([A-Z0-9]{10,})\s*$",
        r"(?i)\bBY TRANSFER/MPSP2A(\d{9,20})\b",
        r"(?i)^\s*TO TRANSFER/NEFT.*?(\S+)\s*$",
        r"(?i)^\s*TO TRANSFER/(?:NEFT|RTGS).*?(\S+),?$",
        r"(?i)^\s*TO TRANSFER/PS/P2A/(\d+)/",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)^MB-IMPS-DR\b.*?Chq:\s*(\d+)",
        r"(?i)\bMB\s+NEFT\s+DR\s+([A-Z][A-Z0-9]{15})\b",
        r"(?i)^MB\/.*CANARA\/\/(\d+)\s\/",
        r"(?i)^MB\/.*?SELF\/\s*(\d+)\/",
        r"(?i)^MB/.*?/(\d+)(?=/\s*\d{2}\/\d{2}\/\d{4})",
        r"(?i)^MOB-IMPS-CR\b.*?(\d+)(?=\s*(?:Chq:|,|$))",
        r"(?i)^NEFT SREE DHARANI ENTER\s*(?:/XUTR/)?\s*(IOBAN\d+)",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{9,20})",
        r"(?i)\bINET-IMPS-CR/.*?/\d{2}/\d{2}/\d{4}\s?\d{2}:\d{2}:\d{2}/(\d{9,20})",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,16})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)CANARA\/\/(\d+)\/",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
    ],
    "IDFC": [
        r"(?i)^RTGS\/([A-Z0-9]+)\/",
        r"(?i)^NEFT\/([A-Z0-9]+)\/",
        r"(?i)^IMPS\/(\d+)\/",
        r"(?i)IMPS-[A-Z]{2,3}/(?:Fund Trf/)?\s*([0-9]{9,18})[ /]",
        r"(?i)IMPS-MOB/Fund Trf/([0-9]{9,18})/",
        r"(?i)\bIMPS/([0-9]{9,18})/",
        r"(?i)^NEFT/([A-Z0-9]+)/",
        r"(?i)^RTGS/([A-Z0-9]+)/",
        r"(?i)UPI/(?:MOB|DR|CR)/([0-9]{9,20})\s*/",
        r"(?i)^IFT/[0-9]+/[^/]*/([0-9]+)(?:/|$)",
        r"(?i)Ref(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "ICICI": [
        r"(?i)\b(?:MMT|MT|FT)[\s\-]*/?\\s*IMPS\s*/\s*([\d ]{6,20})",
        r"(?i)\bRTGS/([A-Z0-9]+)/",
        r"(?i)\bRTGS-([A-Z0-9]+)\s*[-/]",
        r"(?i)\bNEFT-([A-Z0-9]+)\s*[-/]",
        r"(?i)\bBIL/NEFT/([A-Z0-9]+)",
        r"(?i)\bINF/NEFT/([A-Z0-9 ]{5,})/",
        r"(?i)\bEFT[:\-]([A-Z0-9]+)[-/]",
        r"(?i)\b(?:INF|NF)/INFT/(\d{6,15})/",
        r"(?i)NFINFT(\d{6,15})",
        r"(?i)\b(?:BIL|IL)/INFT/([A-Z0-9]+)",
        r"(?i)^UPI/.*?/(?:UPI|Payment from Ph)/.*?/(\d{9,15})",
        r"(?i)^UPI/.*/(\d{9,15})",
        r"(?i)^UPI\/(\d+)\/",
        r"(?i)^EFT-([A-Z0-9]+)-",
        r"(?i)^NEFT-([A-Z0-9]+)-",
        r"(?i)^NEFT:([A-Z0-9]+)\/",
        r"(?i)^MMT\/IMPS\/(\d+)\/",
        r"(?i)^MT\/IMPS\/(\d+)\/",
        r"(?i)^NF\/NEFT\/([A-Z0-9]+)\/",
        r"(?i)^TGS-([A-Z0-9]+)-",
        r"(?i)^TGS\/([A-Z0-9]+)\/",
        r"(?i)Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "HDFC": [
        r"(?i)^NEFT.*?\(Ref#\s*([A-Z0-9]+)\)",
        r"(?i)^NEFT\s+[A-Z]{2}-.*-([A-Z0-9]+)(?:\s|$|\|)",
        r"(?i)^RTGS\s+DR-.*-([A-Z0-9]+)$",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(HDFCN[0-9]{6,})\b",
        r"(?i)\b(HDFCR[0-9]{6,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/(\d{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/[CD]R/(\d{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "CUB": [
        r"(?i):RTGS:UTR:([A-Z0-9]+):",
        r"(?i)^TO ONL IMPSCUB(\d+):",
        r"(?i):UTR:([A-Z0-9]+):",
        r"(?i)^BY NEFT TRF:[A-Z0-9\s]*\s([A-Z0-9]+):",
        r"(?i)^BY ONL\s+(\d+IMPSINB\d+):",
        r"(?i)^BY RTGS TRF:[A-Z0-9\s]+RTGS\s*-\s*([0-9]+):",
        r"(?i)^TO ONL\s+(IMPS[A-Z0-9]+):",
        r"(?i)^TO ONL NEFT:UTR:([A-Z0-9]+):",
        r"(?i)(IMPS[A-Z]{0,4}\d{9,18})",
        r"(?i)\bNEFT:UTR:([A-Z0-9]+):",
        r"(?i)\bRTGS:UTR:([A-Z0-9]+):",
        r"(?i)^BY\s+NEFT\s+TRF:.*\b([A-Z0-9]{11,})\b:",
        r"(?i)^BY\s+RTGS\s+TRF:.*?RTGS\s*-\s*([A-Z0-9]{10,20}):",
        r"(?i)\bUPI/[CD]R/(\d{9,20})/",
        r"(?i)^(?:BY|TO)\s+ONL\s+TRF:\s*CA\s*([0-9]{10,})",
        r"(?i)\(Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)\)",
    ],
    "AXIS": [
        r"(?i)^IMPS/P2A/(\d{6,20})/",
        r"(?i)^UPI/P2[AM]/(\d{6,20})/",
        r"(?i)^INB/RTGS/([A-Z0-9]{10,})/",
        r"(?i)^RTGS/(?:[A-Z]{2}/)?([A-Z0-9]{10,})/",
        r"(?i)^INB/NEFT/([A-Z0-9]+)",
        r"(?i)^NEFT/(?:[A-Z]{2,4}/)?([A-Z0-9]{10,})",
        r"(?i)\bBRN-(?:NEFT|RTGS)-([A-Z0-9]{10,})-",
        r"(?i)^IFT/(?:EMB/)?([A-Z0-9]{10,})/",
        r"(?i)^MOB/(?:SELFFT|TPFT)/[A-Z0-9 ]*/(\d{10,})$",
        r"(?i)Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
    ],
    "FDRL": [
        r"(?i)^RTG\/[^\/]+\/([A-Z0-9]+)\/",
        r"(?i)^NFT\/[^\/]+\/([A-Z0-9]+)\/",
        r"(?i)^RTG\/([A-Z0-9]+)\/",
        r"(?i)^MB\s+FTB\/(\d+)\/",
        r"(?i)MB\s+FTO\/(\d+)\s*\/",
        r"(?i)^IFN\/([A-Z0-9]+)\s",
        r"(?i)^NA\/MB\s+FTB\/(\d+)\/",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bFDRL[A-Z0-9]{8,}",
        r"(?i)\bFDRLINB[A-Z0-9]{6,}",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{9,20})",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,16})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "KVB": [
        r"(?i)^IMPS-(\d+)-",
        r"(?i)^MB-OWN-DR:.*-(\d+)(?:-[a-z]+|-)$",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(KVBLH[0-9]{8,})\b",
        r"(?i)\b(KVBLR[0-9]{8,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
        r"(?i)^([0-9A-Fa-f]{16})",
    ],
    "SBI": [
        r"(?i)^BY TRANSFER.*?RTGS UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY TRANSFER-NEFT\*[A-Z0-9\s]+\*([A-Z0-9]+)\s*\*",
        r"(?i)^(?:BY|TO)\s+TRANSFER-RTGS UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)BY\s+TRANSFER-([A-Z0-9]+)\s*-",
        r"(?i)^TO TRANSFER-IMPS\/(\d+)\s*\/",
        r"(?i)^TO TRANSFER-INB NEFT UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(SBIN[0-9A-Z]{8,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
        r"(?i)\(Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)\)",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
    ],
    "IOB": [
        r"(?i)^TRANSFER\s+FROM\s+[A-Z0-9]+\s+NEFT\/[A-Z0-9]+\/([A-Z0-9]+)\/",
        r"(?i)^BY TRANSFER\s+NEFT\/[A-Z0-9]+\/([A-Z0-9]+)\s*\/",
        r"(?i)^BY TRANSFER\s+RTGS\/[A-Z0-9]+\/([A-Z0-9\s]+)\/",
        r"(?i)NEFT\/[A-Z0-9]+\/([A-Z0-9]+)\/",
        r"(?i)^NEFT-[A-Z]+-([A-Z0-9]+)-",
        r"(?i)^RTGS-[A-Z]+-([A-Z0-9]+)-",
        r"(?i)^NBC\/IMPS\/(\d+)\/",
        r"(?i)^MT\/IMPS\/(\d+)\/",
        r"(?i)NET@(\d+)$",
        r"(?i)^TRTR\/(\d+)\/",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(IOBAN[0-9]{8,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
        r"(?i)\(Ref#\s*([A-Z0-9]+)\)",
    ],
    "IDIB": [
        r"(?i)^TRANSFER TO .*?//IMPS/P2A/(\d{12})",
        r"(?i)^TRANSFER TO .*?/(?:NEFT|RTGS)/[^/]+/([A-Z0-9]+)/",
        r"(?i)^TRANSFER FROM\s+\d+\s*/IMPS/P2A/(\d{12})/",
        r"(?i)^TRANSFER FROM .*?(?:NEFT|RTGS)/[^/]+/([A-Z0-9]+)/",
        r"(?i)^.?TRANSFER FROM\s+\d+/\s([^/]+?)\s*/",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)RTGS\/[A-Z0-9]+\/([A-Z0-9]+)\/",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(IDIB[HN][0-9]{8,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)Mobile\/(\d+)\/",
        r"(?i)Mobile\s*\/\s*(\d+)\/",
        r"(?i)\bUPI/(?:DR|CR)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "BOB": [
        r"(?i)^BY TRANSFER.*?RTGS UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY TRANSFER.*?NEFT UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY TRANSFER.*?UPI UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY TRANSFER.*?IMPS UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY TRANSFER.*?UTR NO:\s*([A-Z0-9]+)-",
        r"(?i)\bMMSRE/[A-Z0-9]+/[^/]*/(\d{9,20})\b",
        r"(?i)\bEBANK:(?:SELF|QT|WIB)/(\d+)(?:/|$)",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(?:I?NEFT|RTGS)-([A-Z0-9]{12,})-",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)MBK/.*?/(\d{9,20})/\d{2}:\d{2}:\d{2}/",
        r"(?i)(?:IMPS|MBK).*?(\d{12})",
        r"(?i)\bIMPSIB/(\d{9,20})/TRANSFER\b",
        r"(?i)\bIMPS(?:\s*P2[AM])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF NO\.?|RRN)[:\-\s]*([A-Z0-9]{9,20})",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,16})",
        r"(?i)^UPI.*?([0-9]{9,16})",
        r"(?i)P2A/(\d{12})/",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "INDB": [
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(INDB[A-Z0-9]{6,})\b",
        r"(?i)^FT\/(\d+)\/",
        r"(?i)INDUSIND ACCOUNT\/([A-Z0-9]+)\/",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "BOI": [
        r"(?i)^BY TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bIMPS(?:IB|UAMB)/(\d{9,20})/",
        r"(?i)\b(?:StCon|tCon)-(\d+)/",
        r"(?i)\bUNAMB/[^/]+/(\d{9,20})/Ark\b",
        r"(?i)UNAMB\/[^\/]+\/(\d+)\/",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF NO\.?|RRN)[:\-\s]*([A-Z0-9]{9,20})",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,16})",
        r"(?i)^UPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "DBS": [
        r"(?i)^UPI TXN:\s*/(\d{9,20})-",
        r"(?i)^IMPS DR\.:.*:(\d{9,20})\s*$",
        r"(?i)^TRANSFER IMPS-P2[A-Z]-([0-9]{9,20})-",
        r"(?i)^TRANSFER IMPS-([0-9]{9,20})-",
        r"(?i)^IMP-([0-9]{9,20})-",
        r"(?i)IMPS([0-9]{9,30})\s",
        r"(?i)^TRANSFER RTGS\s+([A-Z0-9]{10,})",
        r"(?i)^TRANSFER NEFTIN\s+([A-Z0-9]{10,})",
        r"(?i)^TRANSFER NEFT\s+([A-Z0-9]{10,})",
        r"(?i)^TRANSFER TRANSFER\s+(\d{4}RF\d{4,})",
        r"(?i)^NET TXN:.*?/(\d{10,})\s*$",
        r"(?i)Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "JSFB": [
        r"(?i)\bNEFT\s+DR-([A-Z0-9]+)",
        r"(?i)\bIMPS\s+(\d{9,15})\b",
        r"(?i)\bUPI/(?:CR|DR)/(\d{9,20})/",
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(JSFB[A-Z0-9]{6,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "KKBK": [
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(KKBKH[0-9]{8,})\b",
        r"(?i)\b(KKBKR[0-9]{8,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bSentIMPS([0-9]{12})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "PNB": [
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(PUNBR[0-9 ]{9,})\b",
        r"(?i)\b(PUNBH[0-9 ]{5,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "RBL": [
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(RATN[0-9A-Z]{7,})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "SIB": [
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bNEFT TO:([A-Z0-9]+):",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)^RTGS\s+TO:([A-Z0-9]+):",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)MOB\/(\d+)",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "TMB": [
        r"(?i)^BY\s+TRANSFER.*?(?:RTGS|NEFT|IMPS|UPI)\s+UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)^BY\s+TRANSFER.*?UTR\s+NO:\s*([A-Z0-9]+)-",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bNEFT/[^/]+/([A-Z0-9]{10,})",
        r"(?i)^RTGS\/[^\/]+\/([A-Z0-9]+)",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\b(TMBLH[0-9]{8,})\b",
        r"(?i)\b(TMBLR[0-9]{8,})\b",
        r"(?i)\b(TMBL[0-9]{8,})\b",
        r"(?i)^eBank\/IMPSP2A.*?\/(\d+)\/self",
        r"(?i)^MBank\/IMPSP2A\s+To\s+[^\/]+\/(\d+)\/",
        r"(?i)^MBank\/(\d+)\/",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)[:\-\s]*([A-Z0-9]{8,20})",
        r"(?i)\bIMPS\s*/\s*P2[AMP]/([0-9]{9,16})",
        r"(?i)\bIMPS(?:\s*P2[AMP])?[-/\s]*([0-9]{9,16})\b",
        r"(?i)\bIMPS/[^/]+/([0-9]{9,20})(?:/|$)",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/([0-9]{9,20})/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)[:\-\s]*([0-9]{9,20})",
        r"(?i)\bUPI.*?([0-9]{9,16})",
        r"(?i)^UPI\/(\d+)\/",
        r"(?i)\bRef(?:erence)?\s*(?:No\.?|#)?[:\-\s]*([A-Z0-9]*\d[A-Z0-9]*)",
    ],
    "UBI": [
        r"(?i)^BY TRANSFER.?RTGS UTR NO[:\s-]([A-Z0-9]{10,30})",
        r"(?i)\bBY\s+NEFT\s+TRF:.*?\b([A-Z0-9]{10,30}):",
        r"(?i)\bRTGS\s*-\s*([0-9]{12,20})",
        r"(?i)/(?:NEFT|RTGS)/[^/]+/([A-Z0-9]{10,30})/",
        r"(?i)/IMPS/P2A/(\d{10,16})/",
        r"(?i)\bIMPS(?:\s*RRN)?[:\s\-]*([0-9]{9,16})\b",
        r"(?i)\b(\d+IMPSINB\d+)\b",
        r"(?i)\bIMPSA[BR]\/(\d{12})\/",
        r"(?i)\b(IMPSCUB\d+)\b",
        r"(?i)\bTO\s+ONL\s+(IMPS[A-Z0-9]+):",
        r"(?i)\b(?:BY|TO)\s+ONL\s+([A-Z0-9]+):",
        r"(?i)\bUTR(?:\s*NO\.?)?[:\-]\s*([A-Z0-9]{10,30})",
        r"(?i)MOBFT\s+(?:from|to):\s+.*?\/(\d+)$",
        r"(?i)^(?:UPIAB|UPIAR)\/(\d+)\s*\/",
        r"(?i)\b(?:RRN|REF(?:ERENCE)?(?:\s*NO\.?)?)[:\s\-]*([A-Z0-9]{6,20})\b",
    ],
    "YBL": [
        r"(?i)/IMPS/P2A/(\d{10,16})/",
        r"(?i)/(?:NEFT|RTGS)/[^/]+/([A-Z0-9]{10,30})/",
        r"(?i)\b(?:BY|TO)\s+ONL\s+([A-Z0-9]+):",
        r"(?i)\bTO\s+ONL\s+(IMPS[A-Z0-9]+):",
        r"(?i)\bBY\s+NEFT\s+TRF:.*?\b([A-Z0-9]{10,30}):",
        r"(?i)\bRTGS\s*-\s*([0-9]{12,20})",
        r"(?i)\bRTGS\s+UTR\s*NO[:\s-]*([A-Z0-9]{10,30})",
        r"(?i)\bUTR(?:\s*NO\.?)?[:\-]\s*([A-Z0-9]{10,30})",
        r"(?i)\bRRN[:\s\-]*([0-9]{9,16})\b",
        r"(?i)\b(\d+IMPSINB\d+)\b",
        r"(?i)\b(IMPSCUB\d+)\b",
        r"(?i)\b(?:RRN|REF(?:ERENCE)?(?:\s*NO\.?)?)[:\s\-]*([A-Z0-9]{6,20})\b",
    ],
    "BDBL": [
        r"(?i)^IMPS-([0-9]+)-",
        r"(?i)^UPI\/CR\/([A-Z0-9]+)\/",
        _REF_PATTERN,
    ],
    "IDBI": [
        r"(?i)^UPI\/(\d+)\/",
        _REF_PATTERN,
    ],
    "HSBC": [
        r"(?i)\bIMPS,\s*(\d{12})\b",
        _REF_PATTERN,
    ],
    "UJVN": [
        r"(?i)IMPS[-/\s]*([0-9]{9,16})",
        _REF_PATTERN,
    ],
    "CBI": [
        r"(?i)IMPS(?:P2A)?[-/\s]*([0-9]{9,16})",
        _REF_PATTERN,
    ],
    "COMMON": [
        r"(?i)\bIMPS/[^/]+/(\d{9,20})/",
        r"(?i)\bIMPS\s*/\s*P2A\s*/\s*(\d{9,20})",
        r"(?i)\b(?:FT|MB)\s+IMPS/[A-Z]+/(\d{9,20})\b",
        r"(?i)\bIMPS\s+(\d{9,20})\b",
        r"(?i)\bIMPS\s+(?:REF(?:ERENCE)?\s*NO\.?|REF\s*NO\.?|RRN)\s*[:\-]?\s*([A-Z0-9]{8,20})",
        r"(?i)\bNEFT\s+DR-([A-Z0-9]+)",
        r"(?i)\bNEFT/([A-Z0-9]*\d[A-Z0-9]{5,})/[^/]*",
        r"(?i)\bNEFT/[^/]+/([A-Z0-9]*\d[A-Z0-9]{5,})\b",
        r"(?i)\bNEFT\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS\s+UTR\s+NO[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bUTR\s*(?:NO)?[:\-\s]*([A-Z0-9]{10,22})",
        r"(?i)\bRTGS/(?:[A-Z]{2}/)?([A-Z0-9]{10,})",
        r"(?i)^RTGS-([A-Z0-9]{10,})",
        r"(?i)\bUPI/(?:DR|CR|P2A|P2M)/(\d{9,20})/",
        r"(?i)\bUPI[A-Z]{2}/(\d{9,20})/",
        r"(?i)\bUPI/(\d{9,20})\s*/UPI/",
        r"(?i)\bUPI.*?\b(?:UTR|RRN|REF(?:ERENCE)?\s*NO\.?)\s*[:\-]?\s*([0-9]{9,20})",
        r"(?i)\(Ref#\s*([A-Z0-9]*\d[A-Z0-9]*)\)",
    ],
}

# Banks that only need the common ref# fallback
_REF_ONLY_BANKS = ('UCO', 'CSB', 'DEUT', 'BOM', 'AUBL', 'KARB', 'ESFB',
                   'DLXB', 'CITI', 'SCB', 'DCB', 'ESAF', 'JAKA', 'PSIB')
for _b in _REF_ONLY_BANKS:
    _RAW_PATTERNS[_b] = [_REF_PATTERN]

# ── Pre-compile all patterns once at import time ───────────────────────────────
# Keeps the public `pattern` name for backward compatibility.
pattern: dict[str, list[re.Pattern]] = {
    bank: [re.compile(p) for p in pats]
    for bank, pats in _RAW_PATTERNS.items()
}


# ── Private search helper ──────────────────────────────────────────────────────

def _search(desc: str, compiled_patterns: list) -> str | None:
    """Try each compiled pattern against *desc*; return first group-1 match."""
    for rx in compiled_patterns:
        try:
            m = rx.search(desc)
            if m:
                return m.group(1).replace('/', '').strip()
        except (IndexError, Exception):
            continue
    return None


# ── Public API ─────────────────────────────────────────────────────────────────

def extract_using_common(desc) -> str | None:
    """Extract a reference number using the COMMON pattern list."""
    desc = '' if pd.isna(desc) else str(desc).replace('\\', '')
    return _search(desc, pattern['COMMON'])


def extract_imps(desc, bank: str | None = None) -> str | None:
    """
    Extract an IMPS/NEFT/RTGS/UPI reference number from *desc*.
    Falls back to COMMON patterns if no bank-specific match is found.
    """
    desc = '' if pd.isna(desc) else str(desc).replace('\\', '')

    if bank:
        bank = _BANK_ALIASES.get(bank, bank)
        if bank in pattern:
            result = _search(desc, pattern[bank])
            if result is not None:
                return result

    return extract_using_common(desc)